### PR TITLE
feat: validate payload input and output

### LINKED ISSUE #26: d2g binary doesn't validate input against Docker Worker schema
Note, this only applies to the d2g binary executable itself. The d2g go library (that generic-worker will import) inputs and outputs native go types, and therefore payload validation is not the responsibility of the d2g library, but will be generic-worker's responsibility before it calls the d2g library.

So this issue only affects the _main_ package, and not the _d2g_ package (i.e. cmd/d2g/main.go).

It might be a little fiddly to implement, since the main method json-decodes and consumes the standard input as a continuous stream. It may therefore require creating a pipe in order for the json decoder and the json schema validator to both process the same input, and also we'll need to detect when the input is complete in order to know we have all the bytes that we need to pass to gojsonschema to check that the input is valid.

Once we migrate to generic-worker, this won't be an issue, as generic-worker will validate the inputs before it calls the d2g library. However, the d2g binary may prove to be useful for a while to come and aid with the transformation of docker-worker payloads to generic-worker, avoiding the need for generic-worker to convert them internally. So it is probably still worth adding, as long as the d2g cli tool is actively used for converting payloads.

### PR DESCRIPTION
**Pull request by matt-boris**
Fixes #26
Screenshot 2023-06-01 at 10 30 36 AM

### CODE REVIEW

**Review by lotas — DISMISSED** [review]
nice

**Comment by petemoore** [comment]
Here is the code in generic-worker, in case you can reuse any of it: https://github.com/taskcluster/taskcluster/blob/d768d4a65a87215a830aa292fe0fcd08656d5f31/workers/generic-worker/gw-codegen/main.go#L99-L118

**Comment by matt-boris** [comment]
Converting to draft for now as I also am going to add result validation. Ensuring that the generic worker payload is a valid schema as well 👍🏻

**Review by petemoore — APPROVED** [review]
Awesome!!

**Pull request merged**
